[tool.pytest.ini_options]
minversion = 6.0
addopts = "-ra"
testpaths =[
    "tests",
    "integration",
]

[tool.poetry]
name = "f1tenth_gym"
version = "1.0.0dev"
description = "Gym environment for F1TENTH"
license = "MIT"
authors = [
    "Hongrui Zheng",
    "Renukanandan Tumu",
    "Luigi Berducci",
    "Ahmad Amine",
    "Joseph Auckley",
    "Matthew O'Kelly",
    "Aman Sinha"
]
maintainers = [
    "Hongrui Zheng",
]
readme = "README.md"
homepage = "https://f1tenth.org"
repository = "https://github.com/f1tenth/f1tenth_gym"
documentation = "https://f1tenth-gym.readthedocs.io/en/latest/"
packages = [
    {include = "f1tenth_gym"},
]

[tool.poetry.dependencies]
python = ">=3.9"
gymnasium = "^1.0.0"
numpy = "^1.26.4"
pillow = "^11.2.1"
scipy = "^1.13.1"
numba = "^0.60.0"
PyYAML = "^6.0.2"
pygame = "^2.6.1"
opencv-python = "^4.11.0.86"
yamldataclassconfig = "^1.5.0"
requests = "^2.32.4"
shapely = "^2.0.7"
pyqtgraph = "^0.13.7"
PyQt6 = "^6.9.1"
torch = "^2.7.1"
stable-baselines3 = "^2.6.0"
ray = {extras = ["rllib", "tune"], version = "^2.46.0"}
optuna = "^4.9.0"
tensorboard = "^2.19.0"
pandas = "^2.3.0"
matplotlib = "^3.9.4"
moviepy = "^2.2.1"
networkx = "^3.2.1"
tqdm = "^4.67.1"
Jinja2 = "^3.1.6"
dataclasses-json = "^0.6.7"
python-dotenv = "^1.1.0"
pyarrow = "^20.0.0"
tensorboardX = "^2.6.2.2"
dm-tree = "^0.1.8"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.4"
black = "^23.12.1"
ipykernel = "^6.29.0"
isort = "^5.13.2"
autoflake = "^2.2.1"
matplotlib = "^3.8.2"
flake8 = "^7.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
