# ——— Anchors definitions ———
# This file defines the configuration for multiple experiments in a multi-agent reinforcement learning setup.
# This are the anchors used to avoid repetition in the YAML file.
# Anchors are used to define common configurations that can be reused across different experiments.

# Global configuration
num_cpus: 20  # Number of CPUs for Ray to use
num_env_runners: 14  # Number of parallel processes (<= CPUs)
num_envs_per_env_runner: 6  # Vectorized environments per process

training: &training
  timesteps_total: 2_000_000
  eval_interval:    2000
  reward_function:  ProgressRewardEnv

evaluation: &evaluation
  episodes: 5

env: &env
  map:               oval_small
  num_agents:        2
  timestep:          0.01
  num_beams:         36
  integrator:        rk4
  control_input:     [speed, steering_angle]
  observation_config: { type: original }
  reset_config:       { type: cl_grid_static }
  render_mode:        null

# https://arxiv.org/html/2403.07129v1#S4.E10
ppo_params: &ppo_params
  # Basic hyperparameters
  gamma:                        0.99
  lr:                          0.0001
  
  # Learning rate schedule
  lr_schedule:                 [[0, 0.0001], [30000000, 0.0]]  # Cosine schedule approximation
  
  # Batch and trajectory configuration
  train_batch_size:            512
  # rollout_fragment_length:     2048
  
  # Policy optimization
  clip_param:                  0.1
  num_sgd_iter:                7
  minibatch_size:              512
  
  # Value function
  vf_loss_coeff:               0.5
  
  # GAE and advantage estimation
  use_gae:                     true
  lambda_:                     0.95
  
  # Gradient clipping
  grad_clip:                   1.0
  
  # Neural network initialization
  model:
    fcnet_hiddens:             [256, 256]
    fcnet_activation: "relu"
    fcnet_weights_initializer: "truncated_normal"
    fcnet_weights_initializer_config: {"std": 0.7}
  
  # Environment configuration
  environment:                 { normalize_actions: true }

# https://proceedings.neurips.cc/paper_files/paper/2024/file/b91ea2ba1b6521940e204b7b81d5ef47-Paper-Datasets_and_Benchmarks_Track.pdf#:~:text=Checkpoint%20frequency%20200%2C000%20Discount%20factor,Target%20update%20coefficient%200.005
sac_params: &sac_params
  # Basic hyperparameters
  gamma:                         0.992
  lr:                           0.0003
  # policy_lr:                    0.0003
  # q_lr:                         0.0003
  # alpha_lr:                     0.0003
  
  # Batch and buffer configuration
  train_batch_size:             128
  
  # Update configuration
  training_intensity:           1
  
  # N-step learning
  n_step:                       3
  
  # Target network update
  tau:                          0.005
  
  # Q-function configuration
  twin_q:                       true
  
  # Neural network architecture
  model:
    fcnet_hiddens:              [256, 256, 256]
  q_model_config:
    fcnet_hiddens:              [256, 256, 256]
  policy_model_config:
    fcnet_hiddens:              [256, 256, 256]
  
  # Misc
  target_entropy:               auto
  environment:                  { normalize_actions: true }
  replay_buffer_config:         { type: MultiAgentPrioritizedReplayBuffer, capacity: 10000000 }

# ——— List of experiments ———
experiments:

  # ——— Catalunya experiments ———
  # PPO experiments with Catalunya
  - name: Catalunya_PPO_Individual_Policy_ProgressRewardAdvanced
    storage_path: ../models_deposito
    training:
      <<: *training
      algorithm:     PPO
      shared_policy: false
      reward_function: ProgressRewardAdvancedEnv
    evaluation:
      <<: *evaluation
    env:
      <<: *env
      map: Catalunya
    ppo_params:
      <<: *ppo_params

  - name: Catalunya_PPO_Individual_Policy_SpeedReward
    storage_path: ../models_deposito
    training:
      <<: *training
      algorithm:     PPO
      shared_policy: false
      reward_function: SpeedRewardEnv
    evaluation:
      <<: *evaluation
    env:
      <<: *env
      map: Catalunya
    ppo_params:
      <<: *ppo_params

  - name: Catalunya_PPO_Individual_Policy_WaypointReward
    storage_path: ../models_deposito
    training:
      <<: *training
      algorithm:     PPO
      shared_policy: false
      reward_function: WaypointRewardEnv
    evaluation:
      <<: *evaluation
    env:
      <<: *env
      map: Catalunya
    ppo_params:
      <<: *ppo_params

  - name: Catalunya_PPO_Individual_Policy_SafetyReward
    storage_path: ../models_deposito
    training:
      <<: *training
      algorithm:     PPO
      shared_policy: false
      reward_function: SafetyRewardEnv
    evaluation:
      <<: *evaluation
    env:
      <<: *env
      map: Catalunya
    ppo_params:
      <<: *ppo_params

  # SAC experiments with Catalunya
  - name: Catalunya_SAC_Individual_Policy_ProgressRewardAdvanced
    storage_path: ../models_deposito
    training:
      <<: *training
      algorithm:     SAC
      shared_policy: false
      reward_function: ProgressRewardAdvancedEnv
    evaluation:
      <<: *evaluation
    env:
      <<: *env
      map: Catalunya
    sac_params:
      <<: *sac_params

  - name: Catalunya_SAC_Individual_Policy_SpeedReward
    storage_path: ../models_deposito
    training:
      <<: *training
      algorithm:     SAC
      shared_policy: false
      reward_function: SpeedRewardEnv
    evaluation:
      <<: *evaluation
    env:
      <<: *env
      map: Catalunya
    sac_params:
      <<: *sac_params

  - name: Catalunya_SAC_Individual_Policy_WaypointReward
    storage_path: ../models_deposito
    training:
      <<: *training
      algorithm:     SAC
      shared_policy: false
      reward_function: WaypointRewardEnv
    evaluation:
      <<: *evaluation
    env:
      <<: *env
      map: Catalunya
    sac_params:
      <<: *sac_params

  - name: Catalunya_SAC_Individual_Policy_SafetyReward
    storage_path: ../models_deposito
    training:
      <<: *training
      algorithm:     SAC
      shared_policy: false
      reward_function: SafetyRewardEnv
    evaluation:
      <<: *evaluation
    env:
      <<: *env
      map: Catalunya
    sac_params:
      <<: *sac_params