# ——— Anchors definitions ———
# This file defines the configuration for multiple experiments in a multi-agent reinforcement learning setup.
# This are the anchors used to avoid repetition in the YAML file.
# Anchors are used to define common configurations that can be reused across different experiments.
training: &training
  timesteps_total: 3_000_000
  eval_interval:    2000
  reward_function:  KohondaMultiAgentF110Env

evaluation: &evaluation
  episodes: 5

env: &env
  map:               oval_small
  num_agents:        2
  timestep:          0.01
  num_beams:         36
  integrator:        rk4
  control_input:     [speed, steering_angle]
  observation_config: { type: original }
  reset_config:       { type: cl_grid_static }
  render_mode:        null

ppo_params: &ppo_params
  gamma:            0.99
  lr:               0.00005
  train_batch_size: 4000
  environment:      { normalize_actions: true }

sac_params: &sac_params
  tau:                   0.005
  target_entropy:        auto
  alpha_lr:              0.0003
  environment:           { normalize_actions: true }
  replay_buffer_config:  { type: MultiAgentPrioritizedReplayBuffer }

# ——— List of experiments ———
experiments:
  - name: oval_small_PPO_Shared_Policy
    storage_path: ../models
    training:
      <<: *training
      algorithm:     PPO
      shared_policy: true
    evaluation:
      <<: *evaluation
    env:
      <<: *env
    ppo_params:
      <<: *ppo_params

  - name: oval_small_PPO_Individual_Policies
    storage_path: ../models
    training:
      <<: *training
      algorithm:     PPO
      shared_policy: false
    evaluation:
      <<: *evaluation
    env:
      <<: *env
    ppo_params:
      <<: *ppo_params

  - name: oval_small_SACK_Shared_Policy
    storage_path: ../models
    training:
      <<: *training
      algorithm:     SAC
      shared_policy: true
    evaluation:
      <<: *evaluation
    env:
      <<: *env
    sac_params:
      <<: *sac_params

  - name: oval_small_SAC_Individual_Policies
    storage_path: ../models
    training:
      <<: *training
      algorithm:     SAC
      shared_policy: false
    evaluation:
      <<: *evaluation
    env:
      <<: *env
    sac_params:
      <<: *sac_params

  - name: oval_small_SAC_Shared_Policy
    storage_path: ../models
    training:
      <<: *training
      algorithm:     SAC
      shared_policy: true
    evaluation:
      <<: *evaluation
    env:
      <<: *env
    sac_params:
      <<: *sac_params

  
  
  - name: Spielberg_PPO_Shared_Policy
    storage_path: ../models
    training:
      <<: *training
      algorithm:     PPO
      shared_policy: true
    evaluation:
      <<: *evaluation
    env:
      <<: *env
      map: Spielberg
    ppo_params:
      <<: *ppo_params

  - name: Spielberg_PPO_Individual_Policies
    storage_path: ../models
    training:
      <<: *training
      algorithm:     PPO
      shared_policy: false
    evaluation:
      <<: *evaluation
    env:
      <<: *env
      map: Spielberg
    ppo_params:
      <<: *ppo_params

  - name: Spielberg_SAC_Shared_Policy
    storage_path: ../models
    training:
      <<: *training
      algorithm:     SAC
      shared_policy: true
    evaluation:
      <<: *evaluation
    env:
      <<: *env
      map: Spielberg
    sac_params:
      <<: *sac_params

  - name: Spielberg_SAC_Individual_Policies
    storage_path: ../models
    training:
      <<: *training
      algorithm:     SAC
      shared_policy: false
    evaluation:
      <<: *evaluation
    env:
      <<: *env
      map: Spielberg
    sac_params:
      <<: *sac_params

  - name: Monza_PPO_Shared_Policy_Convergence
    storage_path: ../models
    training:
      <<: *training
      algorithm:     PPO
      shared_policy: true
    evaluation:
      <<: *evaluation
    env:
      <<: *env
      map: Monza
    ppo_params:
      <<: *ppo_params

  - name: Monza_PPO_Individual_Policies_Convergence
    storage_path: ../models
    training:
      <<: *training
      algorithm:     PPO
      shared_policy: false
    evaluation:
      <<: *evaluation
    env:
      <<: *env
      map: Monza
    ppo_params:
      <<: *ppo_params
  
  - name: Monza_SAC_Shared_Policy_Convergence
    storage_path: ../models
    training:
      <<: *training
      algorithm:     SAC
      shared_policy: true
    evaluation:
      <<: *evaluation
    env:
      <<: *env
      map: Monza
    sac_params:
      <<: *sac_params

  - name: Monza_SAC_Individual_Policies_Convergence
    storage_path: ../models
    training:
      <<: *training
      algorithm:     SAC
      shared_policy: false
    evaluation:
      <<: *evaluation
    env:
      <<: *env
      map: Monza
    sac_params:
      <<: *sac_params

  - name: Catalunya_PPO_Shared_Policy_Convergence
    storage_path: ../models
    training:
      <<: *training
      algorithm:     PPO
      shared_policy: true
    evaluation:
      <<: *evaluation
    env:
      <<: *env
      map: Catalunya
    ppo_params:
      <<: *ppo_params

  - name: Catalunya_PPO_Individual_Policies_Convergence
    storage_path: ../models
    training:
      <<: *training
      algorithm:     PPO
      shared_policy: false
    evaluation:
      <<: *evaluation
    env:
      <<: *env
      map: Catalunya
    ppo_params:
      <<: *ppo_params
  
  - name: Catalunya_SAC_Shared_Policy_Convergence
    storage_path: ../models
    training:
      <<: *training
      algorithm:     SAC
      shared_policy: true
    evaluation:
      <<: *evaluation
    env:
      <<: *env
      map: Catalunya
    sac_params:
      <<: *sac_params

  - name: Catalunya_SAC_Individual_Policies_Convergence
    storage_path: ../models
    training:
      <<: *training
      algorithm:     SAC
      shared_policy: false
    evaluation:
      <<: *evaluation
    env:
      <<: *env
      map: Catalunya
    sac_params:
      <<: *sac_params

  - name: Silverstone_PPO_Shared_Policy_Convergence
    storage_path: ../models
    training:
      <<: *training
      algorithm:     PPO
      shared_policy: true
    evaluation:
      <<: *evaluation
    env:
      <<: *env
      map: Silverstone
    ppo_params:
      <<: *ppo_params

  - name: Silverstone_PPO_Individual_Policies_Convergence
    storage_path: ../models
    training:
      <<: *training
      algorithm:     PPO
      shared_policy: false
    evaluation:
      <<: *evaluation
    env:
      <<: *env
      map: Silverstone
    ppo_params:
      <<: *ppo_params
  
  - name: Silverstone_SAC_Shared_Policy_Convergence
    storage_path: ../models
    training:
      <<: *training
      algorithm:     SAC
      shared_policy: true
    evaluation:
      <<: *evaluation
    env:
      <<: *env
      map: Silverstone
    sac_params:
      <<: *sac_params

  - name: Silverstone_SAC_Individual_Policies_Convergence
    storage_path: ../models
    training:
      <<: *training
      algorithm:     SAC
      shared_policy: false
    evaluation:
      <<: *evaluation
    env:
      <<: *env
      map: Silverstone
    sac_params:
      <<: *sac_params