# --- General experiment settings ---
experiment_name: f1tenth_multiagent_SAC
storage_path: ../models # Relative path to store experiment results
env_config_path: env.yaml

# --- Algorithm configurations ---
ppo_config_path: ppo.yaml
sac_config_path: sac.yaml

# --- Training settings ---
training:
  algorithm: SAC
  reward_function: ProgressRewardEnv
  timesteps_total: 20_000
  eval_interval: 2000

# --- Evaluation settings ---
evaluation:
  episodes: 5