# --- General experiment settings ---
experiment_name: f1tenth_multiagent_ppo
storage_path: /home/sergio/repos/f1_tenth_new_integration/models # Relative path to store experiment results
env_config: env.yaml
ppo_config: ppo.yaml
sac_config: sac.yaml

training:
  timesteps_total: 20_000
  eval_interval: 2000
  reward_function: ProgressRewardEnv
  algorithm: PPO

evaluation:
  episodes: 20