#!/usr/bin/env python3
"""
Model Summary Script

This script provides a summary of all trained models generated by batch_train_all_rewards.py.
It shows the status, file sizes, and basic information about each trained model.

Usage:
    python model_summary.py
    python model_summary.py --storage_path ../models_batch
"""

import argparse
import os
import sys
import datetime


def get_file_size(file_path):
    """Get human readable file size"""
    try:
        size = os.path.getsize(file_path)
        for unit in ['B', 'KB', 'MB', 'GB']:
            if size < 1024.0:
                return f"{size:.1f}{unit}"
            size /= 1024.0
        return f"{size:.1f}TB"
    except (OSError, IOError):
        return "N/A"


def get_directory_size(directory):
    """Get total size of directory"""
    total_size = 0
    try:
        for dirpath, dirnames, filenames in os.walk(directory):
            for filename in filenames:
                filepath = os.path.join(dirpath, filename)
                try:
                    total_size += os.path.getsize(filepath)
                except (OSError, IOError):
                    continue

        for unit in ['B', 'KB', 'MB', 'GB']:
            if total_size < 1024.0:
                return f"{total_size:.1f}{unit}"
            total_size /= 1024.0
        return f"{total_size:.1f}TB"
    except (OSError, IOError):
        return "N/A"


def find_checkpoints(experiment_dir):
    """Find checkpoint files in experiment directory"""
    checkpoints = []
    try:
        for root, dirs, files in os.walk(experiment_dir):
            for file in files:
                if file.endswith('.json') and 'checkpoint' in file:
                    checkpoint_path = os.path.join(root, file)
                    checkpoints.append(checkpoint_path)
    except (OSError, IOError):
        pass
    return checkpoints


def get_model_info(experiment_path):
    """Get information about a trained model"""
    info = {
        'exists': False,
        'size': 'N/A',
        'checkpoints': 0,
        'last_modified': 'N/A',
        'status': 'Not Found'
    }

    if os.path.exists(experiment_path):
        info['exists'] = True
        info['size'] = get_directory_size(experiment_path)

        # Find checkpoints
        checkpoints = find_checkpoints(experiment_path)
        info['checkpoints'] = len(checkpoints)

        # Get last modified time
        try:
            latest_time = 0
            for root, dirs, files in os.walk(experiment_path):
                for file in files:
                    file_path = os.path.join(root, file)
                    try:
                        mtime = os.path.getmtime(file_path)
                        if mtime > latest_time:
                            latest_time = mtime
                    except (OSError, IOError):
                        continue

            if latest_time > 0:
                info['last_modified'] = datetime.datetime.fromtimestamp(latest_time).strftime('%Y-%m-%d %H:%M:%S')
        except (OSError, IOError):
            pass

        # Determine status
        if info['checkpoints'] > 0:
            info['status'] = 'Complete'
        else:
            info['status'] = 'Incomplete'

    return info


def main():
    """Main function to generate model summary"""
    parser = argparse.ArgumentParser(description="Generate summary of trained models")
    parser.add_argument("--storage_path", type=str, default="../models_batch",
                        help="Base path where trained models are stored (default: ../models_batch)")

    args = parser.parse_args()

    storage_path = args.storage_path

    print("=" * 80)
    print("TRAINED MODELS SUMMARY")
    print("=" * 80)
    print(f"Storage Path: {os.path.abspath(storage_path)}")
    print(f"Generated: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("=" * 80)

    if not os.path.exists(storage_path):
        print(f"❌ Storage path does not exist: {storage_path}")
        print("Run batch_train_all_rewards.py first to generate models.")
        return 1

    # Expected reward functions and algorithms
    algorithms = ["PPO", "SAC"]

    # Reward classes from rewards.py
    rewards_py_classes = [
        "ProgressRewardEnv",
        "SpeedRewardEnv",
        "SACBasicReward",
        "SACGeminiReward",
        "SpeedReward",
        "SafetyReward"
    ]

    # Reward classes from rewards_pepe.py
    rewards_pepe_classes = [
        "GeminiReward",
        "SpeedReward",
        "WaypointReward",
        "CompetitiveOvertakingReward"
    ]

    all_reward_classes = rewards_py_classes + rewards_pepe_classes

    # Check each expected model
    total_models = 0
    complete_models = 0
    incomplete_models = 0
    missing_models = 0

    print("\nMODEL STATUS:")
    print("-" * 80)
    print(f"{'Algorithm':<8} {'Reward Function':<25} {'Status':<12} {'Size':<10} {'Checkpoints':<12} {'Last Modified'}")
    print("-" * 80)

    for algorithm in algorithms:
        for reward_func in all_reward_classes:
            total_models += 1
            experiment_name = f"batch_training_{algorithm}_{reward_func}"
            experiment_path = os.path.join(storage_path, experiment_name)

            info = get_model_info(experiment_path)

            # Update counters
            if info['status'] == 'Complete':
                complete_models += 1
                status_icon = "✅"
            elif info['status'] == 'Incomplete':
                incomplete_models += 1
                status_icon = "⚠️"
            else:
                missing_models += 1
                status_icon = "❌"

            print(
                f"{algorithm:<8} {reward_func:<25} {status_icon} {info['status']:<10} {info['size']:<10} {info['checkpoints']:<12} {info['last_modified']}")

    print("-" * 80)

    # Summary statistics
    print("\nSUMMARY:")
    print(f"Total expected models: {total_models}")
    print(f"Complete models: {complete_models} ✅")
    print(f"Incomplete models: {incomplete_models} ⚠️")
    print(f"Missing models: {missing_models} ❌")
    print(f"Success rate: {(complete_models/total_models*100):.1f}%")

    # Storage usage
    if os.path.exists(storage_path):
        total_storage = get_directory_size(storage_path)
        print(f"Total storage used: {total_storage}")

    # List actual directories found
    print("\nACTUAL DIRECTORIES FOUND:")
    print("-" * 40)
    if os.path.exists(storage_path):
        dirs = [d for d in os.listdir(storage_path) if os.path.isdir(os.path.join(storage_path, d))]
        if dirs:
            for d in sorted(dirs):
                dir_path = os.path.join(storage_path, d)
                dir_size = get_directory_size(dir_path)
                checkpoints = len(find_checkpoints(dir_path))
                print(f"{d:<40} {dir_size:<10} {checkpoints} checkpoints")
        else:
            print("No model directories found.")
    else:
        print("Storage directory does not exist.")

    print("=" * 80)

    return 0


if __name__ == "__main__":
    sys.exit(main())
